-- Enable necessary extensions
create extension if not exists pgcrypto;

-- -----------------------------------------------------------------------------
-- 1. ENUMS & TYPES
-- -----------------------------------------------------------------------------
create type app_role as enum ('admin', 'vendor', 'customer');
create type booking_status as enum ('pending', 'confirmed', 'in_progress', 'completed', 'cancelled');

-- -----------------------------------------------------------------------------
-- 2. TABLES
-- -----------------------------------------------------------------------------

-- User Roles (Links auth.users to a role)
create table public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  role app_role not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, role)
);

-- Profiles (Extended user info)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  phone_number text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Service Categories
create table public.service_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Services
create table public.services (
  id bigint generated by default as identity primary key,
  category_id bigint references public.service_categories(id) on delete cascade not null,
  name text not null,
  slug text not null unique,
  description text,
  base_price decimal(10, 2),
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Vendors (Specific details for vendor users)
create table public.vendors (
  id uuid references auth.users on delete cascade primary key,
  business_name text not null,
  description text,
  city text,
  address text,
  rating decimal(3, 2) default 0.0,
  is_verified boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Vendor Services (Which services a vendor offers)
create table public.vendor_services (
  id bigint generated by default as identity primary key,
  vendor_id uuid references public.vendors(id) on delete cascade not null,
  service_id bigint references public.services(id) on delete cascade not null,
  price decimal(10, 2) not null,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (vendor_id, service_id)
);

-- Bookings
create table public.bookings (
  id bigint generated by default as identity primary key,
  customer_id uuid references auth.users on delete cascade not null,
  vendor_id uuid references public.vendors(id) on delete cascade not null,
  service_id bigint references public.services(id) on delete cascade not null,
  status booking_status default 'pending' not null,
  scheduled_at timestamp with time zone not null,
  address text not null,
  notes text,
  total_amount decimal(10, 2),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- -----------------------------------------------------------------------------
-- 3. ROW LEVEL SECURITY (RLS)
-- -----------------------------------------------------------------------------
alter table public.user_roles enable row level security;
alter table public.profiles enable row level security;
alter table public.service_categories enable row level security;
alter table public.services enable row level security;
alter table public.vendors enable row level security;
alter table public.vendor_services enable row level security;
alter table public.bookings enable row level security;

-- Policies (Simplified for development)
create policy "Public read access for categories" on public.service_categories for select using (true);
create policy "Public read access for services" on public.services for select using (true);
create policy "Public read access for vendors" on public.vendors for select using (true);
create policy "Public read access for vendor services" on public.vendor_services for select using (true);

-- User Roles policies
create policy "Users can read own role" on public.user_roles for select using (auth.uid() = user_id);

-- Profiles policies
create policy "Users can read/update own profile" on public.profiles for all using (auth.uid() = id);

-- Bookings policies
create policy "Users can see their own bookings" on public.bookings for select using (auth.uid() = customer_id or auth.uid() = vendor_id);
create policy "Customers can create bookings" on public.bookings for insert with check (auth.uid() = customer_id);

-- -----------------------------------------------------------------------------
-- 4. SEED DATA
-- -----------------------------------------------------------------------------

-- Seed Categories
insert into public.service_categories (name, slug, description, image_url) values
('Electronics', 'electronics', 'Repair and maintenance for electronic devices', 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&q=80'),
('Mechanical', 'mechanical', 'Car and bike repair services', 'https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=800&q=80'),
('Home Services', 'home-services', 'Plumbing, electrical, and cleaning', 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&q=80');

-- Seed Services
-- Electronics
insert into public.services (category_id, name, slug, base_price, image_url) 
select id, 'Mobile Repair', 'mobile-repair', 299.00, 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&q=80' from public.service_categories where slug = 'electronics';
insert into public.services (category_id, name, slug, base_price, image_url) 
select id, 'Laptop Service', 'laptop-service', 499.00, 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&q=80' from public.service_categories where slug = 'electronics';

-- Mechanical
insert into public.services (category_id, name, slug, base_price, image_url) 
select id, 'Car Service', 'car-service', 999.00, 'https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=800&q=80' from public.service_categories where slug = 'mechanical';

-- Home Services
insert into public.services (category_id, name, slug, base_price, image_url) 
select id, 'Plumbing', 'plumbing', 199.00, 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=800&q=80' from public.service_categories where slug = 'home-services';

-- -----------------------------------------------------------------------------
-- 5. CREATE USERS
-- -----------------------------------------------------------------------------

-- Admin User
WITH new_admin AS (
  INSERT INTO auth.users (
    instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at
  ) VALUES (
    '00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated', 'admin@servify.com', crypt('password123', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{"name":"System Admin"}', now(), now()
  ) RETURNING id
)
INSERT INTO public.user_roles (user_id, role) SELECT id, 'admin' FROM new_admin;

-- Vendor User
WITH new_vendor AS (
  INSERT INTO auth.users (
    instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at
  ) VALUES (
    '00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated', 'vendor@servify.com', crypt('password123', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{"name":"John Vendor"}', now(), now()
  ) RETURNING id
),
vendor_profile AS (
  INSERT INTO public.vendors (id, business_name, city, is_verified)
  SELECT id, 'John''s Repairs', 'Mumbai', true FROM new_vendor
  RETURNING id
)
INSERT INTO public.user_roles (user_id, role) SELECT id, 'vendor' FROM new_vendor;

-- Customer User
WITH new_customer AS (
  INSERT INTO auth.users (
    instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at
  ) VALUES (
    '00000000-0000-0000-0000-000000000000', gen_random_uuid(), 'authenticated', 'authenticated', 'customer@servify.com', crypt('password123', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{"name":"Alice Customer"}', now(), now()
  ) RETURNING id
)
INSERT INTO public.user_roles (user_id, role) SELECT id, 'customer' FROM new_customer;
