-- Create Reviews Table
create table public.reviews (
  id bigint generated by default as identity primary key,
  booking_id bigint references public.bookings(id) on delete cascade not null unique,
  customer_id uuid references auth.users on delete cascade not null,
  vendor_id uuid references public.vendors(id) on delete cascade not null,
  rating integer check (rating >= 1 and rating <= 5) not null,
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.reviews enable row level security;

-- Policies
create policy "Public read access for reviews" on public.reviews for select using (true);
create policy "Customers can create reviews" on public.reviews for insert with check (auth.uid() = customer_id);
create policy "Users can update own reviews" on public.reviews for update using (auth.uid() = customer_id);

-- Seed some reviews
insert into public.reviews (booking_id, customer_id, vendor_id, rating, comment)
select 
  b.id,
  b.customer_id,
  b.vendor_id,
  5,
  'Excellent service! Very professional.'
from public.bookings b
where b.status = 'completed'
limit 1;
